#tells the pre-commit tool which checks to run, and which versions.

repos:
  #basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  #black
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

  #ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]

  #isort
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort

  #mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        pass_filenames: false
        args: ["--config-file=pyproject.toml"]
        additional_dependencies:
          - sqlalchemy
          - types-psycopg2
          - fastapi
          - httpx
          - structlog
          - pydantic-settings
          - redis
          - uvicorn
          - python-dotenv
          - anthropic
          - pytest
          - pydantic-settings
          - redis
          - pyyaml
          - types-PyYAML
          - python-dotenv
          - uvicorn
